### ISSUE TITLE
Bladeテンプレートのレイアウト定義の@yieldの説明について

### ISSUE THREAD

**Issue by hiroaki-suzuki** [laravel-ja/ja-docs-5.6#15]
Bladeテンプレートページのレイアウト定義の項で、以下の翻訳となっていますが、セッションではなくセクションかと思います。  原文も確認しましたが、sectionとなっています。

    一方の@yieldディレクティブは指定したセッションの内容を表示するために使用します。

**Comment by HiroKws** [comment]
ありがとうございました。５．６と５．５LTSの指摘箇所を修正しました。readouble.comへの反映作業中です。
