### ISSUE TITLE
サービスプロバイダの精査、にタイポ

### ISSUE THREAD

**Issue by yasuflatland-lf** [laravel-ja/ja-docs-5.6#16]
https://readouble.com/laravel/5.6/ja/lifecycle.html
サービスプロバイダの精査で、「サービスプロバーイダー」とありますが、「サービスプロバイダ」のタイポかと思われます。ご確認ください。

https://readouble.com/laravel/5.6/ja/providers.html
のコード中、コメントも「サービスプロバーダー」となっています。

**Comment by HiroKws** [comment]
ご指摘ありがとうございます。readoble.comへ反映したしました。
