### ISSUE TITLE
Homestead イントロダクションのtypo

### ISSUE THREAD

**Issue by dyoshikawa** [laravel-ja/ja-docs-5.6#17]
いつもお世話になっています。

https://readouble.com/laravel/5.6/ja/homestead.html
「Homestead」の「イントロダクション」項目について、
> HomesteadはWindowsやMac、Linuxシステム上で実行でき、Nginx WebサーバとPHP7.2、PHP7.1、PHP7.0、PHP5.6、MySQL、PostgreSQL、Redis、Memcached、Node、他にも素晴らしいLaravelプリケーションを開発するために必要となるものすべてを含んでいます。

こちらの `Laravelプリケーション` は `Laravelアプリケーション` のtypoと思います。
ご確認下さい。

**Comment by HiroKws** [comment]
ありがとうございました。
