### ISSUE TITLE
コードミス

### ISSUE THREAD

**Issue by akira345** [laravel-ja/ja-docs-5.6#18]
https://readouble.com/laravel/5.6/ja/authentication.html
のイベントセクションにある、アプリケーションに指定されたイベントリスナ
コード中にあるサンプルコード内で、
``` 
      'Illuminate\Auth\Events\Registered' => [
            'App\Listeners\LogRegisteredUser',
        ],
```
が重複している。

**Comment by HiroKws** [comment]
ご指摘ありがとうございます。修正しました。readouble.comで公開してる内容も、修正しました。
