### ISSUE TITLE
Auth\PasswordController　=>  Auth\ResetPasswordController でしょうか？

### ISSUE THREAD

**Issue by sakamata** [laravel-ja/ja-docs-5.6#20]
下記ページの以下の部分typoと思われます。
https://readouble.com/laravel/5.6/ja/passwords.html

>ルート定義
>Laravelはパスワードリセットリンクのメールを送信し、ユーザーのパスワードをリセットするために必要なロジックを全部含んでいる、Auth\ForgotPasswordControllerとAuth\PasswordControllerを用意しています。パスワードリセットに必要な全ルートは、make:auth Artisanコマンドで生成します。

> Auth\PasswordControllerを用意しています。

これは

> Auth\ResetPasswordControllerを用意しています。

と思われます。
ご確認をお願いいたします。

**Comment by HiroKws** [comment]
ありがとうございます。５．７にも同じタイポがありましたので、同時に修正しました。現在、5.6の翻訳はドキュメントメンテナンス期間を過ぎていますので、readouble.comへは即時反映をしていません。只今、5.7の原文変更部分を日本語翻訳へ反映させる作業を行っています。その終了時にまとめてreadouble.comへ反映いたします。しばらくお待ちください。
