### ISSUE TITLE
バリデーションルールalpha,alpha_dash,alpha_numの説明について

### ISSUE THREAD

**Issue by crhg** [laravel-ja/ja-docs-5.6#6]
バリデーションルールalpha,alpha_dash,alpha_numの説明は現在

#### alpha

フィールドが全部アルファベット文字であることをバリデートします。

#### alpha_dash

フィールドが全部アルファベット文字と数字、ダッシュ(-)、下線(_)であることをバリデートします。

#### alpha_num

フィールドが全部アルファベット文字と数字であることをバリデートします。

のようになっていますが、実は「アルファベット文字」はユニコードプロパティのLetterとMark(`[\pL\pM]`)、数字はNumber(`[\pN]`)であって、単なる`[a-zA-Z]`や`[0-9]`ではありません。

原文に忠実に訳すとこうなるのは理解できますが、より明確にするために訳注等の形で説明を追加することはできないでしょうか。

本来なら原文がより明確な内容に更新されるのが理想だとは思いますが、その趣旨の[PR](https://github.com/laravel/docs/pull/3412)は既に提出されていますが取り込まれずにcloseされていますので、せめて日本語版だけでも改善できないかという次第です。

ご検討よろしくお願いします。

**Comment by HiroKws** [comment]
ご指摘の点は、既に気づいているのですが、翻訳和文だけの対処を入れてしまうと管理が大変になります。まれに原文が完全に説明不足だとか、間違っている場合などに入れることはありますが、原則英文に合わせています。

日本語だけの対応は避けています。

ぜひ、原文に対するPRを支持して、取り込まれるように応援してあげてください。
