### ISSUE TITLE
バリデーションルールの「使用可能なバリデーションルール」セクションのルール名は翻訳不要

### ISSUE THREAD

**Issue by hidekuro** [laravel-ja/ja-docs-5.6#7]
原文ページでルール一覧がタイトルケースだったから訳されたのかもしれませんが
https://laravel.com/docs/5.6/validation#available-validation-rules

これらルール名はメソッド名と対応しており、和文だと逆に探しにくくなります。
ここは翻訳しないほうが適切だと思います。

**Comment by HiroKws** [comment]
ご指摘の点は、翻訳時より数年間、ことあるたびに検討しています。

しかしながら、英語が堪能でない人が主に和文を利用します。その点を考えると、どのようなことができるのかという一覧があるのは、悪いことでありません。

また、基本htmlサイトでありますので、何かを探すのであれば、ブラウザの検索機能が利用できます。
